### ISSUE TITLE
Feature Request: Allow Webhooks for Content Transfer

### ISSUE THREAD

**Issue by eco-fastfwd** [umbraco/Umbraco.Heartcore.Issues#68] opened 2022-09-02 14:09 UTC
### Issue description

Allow Webhooks to be generated when content is transferred from One Environment to Another.

**Comment by sitereactor** [comment] 2022-09-05 07:35
Investigate in Sprint 197

**Comment by eco-fastfwd** [comment] 2022-09-20 08:09
Hi @sitereactor,

What I meant was triggering a webhook upon transfer of content. The scenario is we have a content in the development environment and we transferred the specific content into the live environment. However, we have to manually publish it again in live for us to see the changes in our site because the site becomes updated upon calling of webhook. 

This is workable if we only transferred 1 or 2 contents but if we transferred multiple contents in different folders, it becomes time consuming for us. So hopefully, there is a way to trigger a webhook upon the transfer of a content.

**Comment by jmf-umbraco** [comment] 2024-01-15 10:18
We have been unable to reproduce the behaviour described in this ticket. Heartcore should fire webhooks for each content item transferred to an environment using the Content Transfer feature.

If you continue to observe behaviour not in line with the above, please raise a support ticket or re-open this issue. Thanks!

**Closed by jmf-umbraco** 2024-01-15 10:18 UTC
Labels: status/needs-investigation, status/idea, type/feature
