### ISSUE TITLE
Custom doc property is not returned up on the API upon transfer to Live environment

### ISSUE THREAD

**Issue by romeguarin** [umbraco/Umbraco.Heartcore.Issues#105] opened 2023-08-04 03:19 UTC
### Issue description

I have a content that was created in Dev environment that can be retrieved using the Filter API but when it was transferred to Live the same Filter API endpoint and request does not return the said content.

The content has a document type that uses a "key" property. Here's what the content looks like:

<img width="812" alt="Screenshot 2023-08-04 at 12 59 26 pm" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6064432/4e114ca8-584a-4f26-ae1a-f977a95b3c2b">

Here's the request / response sent to Dev environment.

<img width="1034" alt="Screenshot 2023-08-04 at 1 08 26 pm" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6064432/2504db53-edf8-40bb-abcd-b5c0f14f36a5">

While here's how the same values are when pointed to Live environment:

<img width="1038" alt="Screenshot 2023-08-04 at 1 10 25 pm" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6064432/20588657-eced-4be6-a0ab-1f508d587c9e">

Looking into it further I noticed when I try to get the content via Get Content by ID endpoint the response between Development and Live are different, in which the key is missing from the Live environment response.

Here's the Dev response:
<img width="1022" alt="Screenshot 2023-08-04 at 1 14 52 pm" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6064432/3613efd3-f4ef-4128-8644-4b578d8a3d6b">

And here's the Live response:
<img width="1021" alt="Screenshot 2023-08-04 at 1 17 21 pm" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/6064432/debe6591-b9b7-4dcf-9968-8348d5e99067">

I've reported this over the chat support but haven't had any clear response on what's causing the issue.

**Comment by jmf-umbraco** [comment] 2023-08-08 08:03
Hi Jerome,

Thanks for the report. We'll take a look into this and see if we can find an explanation for the behaviour you are seeing.

**Comment by jmf-umbraco** [comment] 2023-11-30 12:08
Hello again @romeguarin,

We have investigated further and have been unable to reproduce this issue on a fresh Heartcore instance. We believe that it may be an invalid cache or something similar affecting only your project.

If you are still experiencing the issue, your best course of action is to reach out to support once more - if you do not receive an answer then please kindly request that they escalate the ticket.

As this does not to be problem for other projects, I will close this issue.

**Closed by jmf-umbraco** 2023-11-30 12:08 UTC
Labels: status/needs-investigation, type/bug
