### ISSUE TITLE
Unable to login if user's group has no content start node

### ISSUE THREAD

**Issue by PascalIcatt** [umbraco/Umbraco.Heartcore.Issues#84] opened 2022-12-22 15:50 UTC
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

heartcore

### Bug summary

After inviting a user to a group without a start node the user is unable to login to the backoffice.
Registration goes fine but after logging in, the user is redirected back to a login page with a blue 'Sign in with Umbraco ID' button is shown.
A popup shows the text 'Logged in with Umbraco Id... please wait...' and does not continue.

After contact with support they discovered this is because the group start nodes were empty.
Adding a start node solved the issue.
Support asked me to submit a bug report here.

### Specifics

Problem accurs in all major browsers.
Happens to users invited in the backoffice

### Steps to reproduce

1: create a group without start nodes
2: invite a user through the backoffice and assign only group from step 1
3: register the user and try to login

### Expected result / actual result

Desired:
User is logged in, even without a start node selected for the assigned user group

Actual bug:
Registration goes fine but after logging in, the user is redirected back to a login page with a blue 'Sign in with Umbraco ID' button is shown.
A popup shows the text 'Logged in with Umbraco Id... please wait...' and does not continue.

**Comment by sitereactor** [comment] 2023-01-09 09:27
Adding here that the specific error message isn't currently supported via Umbraco Id, which is why it doesn't show (_msg "User has no start-nodes"_) for Heartcore and Umbraco Cloud projects.

Personally I'm not sure I understand the use case for having a backoffice user that cannot login to the backoffice - @Zeegaan you mentioned that its expected behavior, so I'm curious to hear the reasoning. Maybe there is a use case I'm not seeing.
Not having a 'start node' could just as well imply that you have access to everything 🤷

**Comment by sitereactor** [comment] 2023-02-06 08:27
Note: if you remove the start-node from the (ie.) admin group then everyone in the admin group will not be able to login and you will be logged out of the backoffice as soon as you click save. This seems like an unfortunate way to lock yourself out of the backoffice, and should be handled by the CMS in a much better way.
We will move this issue back to the CMS tracker with explaination and examples.

**Comment by sitereactor** [comment] 2023-03-20 08:20
Closing this as its a CMS issue. Have discussed it with Bjarke the lead on the CMS team, as they will have to deal with this from their side.

**Closed by sitereactor** 2023-03-20 08:20 UTC
Labels: type/bug
