### ISSUE TITLE
Webhook triggering inconsistencies

### ISSUE THREAD

**Issue by PMendesWebDev** [umbraco/Umbraco.Heartcore.Issues#76] opened 2022-10-26 15:05 UTC
### Issue description

Hey there!

I'm having this issues using webhooks when an umbraco node is published. They both are related so that's why I'll list them in a single issue (if it makes sense, I can split them in two different issues)

1) One is related to webhook actions when culture **invariant** nodes happen to exist in a multilingual structure.

When culture **invariant** node (wherever they may be - root, in between, terminal) is published, the webhook attached to the publish event will be fired as many times as existing languages. It will not fire more than once for any other culture **variant** node.

This is very simple to reproduce: just create an heartcore project with more than one languange, create some nodes that are not culture variant and attach a webhook to the publish event. The webhook logs will present multiple triggers for each language in that invariant node.

2) The other "issue" I have is related to culture variant nodes that share properties. I believe the expected behavior should be something like "if the shared property is changed, the publish event should be fired as many times as existing languages" (one for the node we are changing and others for the culture variants of that node with the updated shared property).

I hope this is easy to understand :) I will, nonetheless, be available to update this issue with any requested information.

All the best!

**Comment by sitereactor** [comment] 2022-11-28 08:46
Hi @PMendesWebDev we'll schedule some time to test out the scenarios you outlined. For number 2 I believe your expectation is correct, but will reply back with some screenshots to outline the expected and actual result, and then we'll take it from there in terms of fixing potential bugs.

**Comment by sitereactor** [comment] 2022-11-28 09:00
>When culture invariant node (wherever they may be - root, in between, terminal) is published, the webhook attached to the publish event will be fired as many times as existing languages. It will not fire more than once for any other culture variant node.

This is correct and expected.
When the node is invariant it will trigger a webhook for each language. 
When the node is variant it will trigger a single webhook for the language you are publishing.

**Comment by sitereactor** [comment] 2023-01-23 08:40
This has been moved to our current sprint and actively worked on. I will report back once its ready for release.

**Comment by sitereactor** [comment] 2023-02-06 08:21
We anticipate getting the updates for this, tested this week.
Will post back when we know when it can be released.

**Comment by sitereactor** [comment] 2023-03-20 08:22
This has been delayed due to other priorities, but we are closing in on a release, which we currently aim for scheduling for release between 28-31. March. I will report back once its scheduled and announced for release on statuspage.

**Comment by jmf-umbraco** [comment] 2024-01-03 10:34
This issue was addressed and released a little while ago. If you continue to see unexpected behaviour in webhooks, please create another issue.

**Closed by jmf-umbraco** 2024-01-03 10:34 UTC
