### ISSUE TITLE
Deployment Error when attempting to deploy a doc type property change

### ISSUE THREAD

**Issue by romeguarin** [umbraco/Umbraco.Heartcore.Issues#106] opened 2023-08-04 06:15 UTC
### Issue description

I've updated a doc type's property to "vary by culture" in Development environment. When I try to deploy it to Live (after deploying to Staging) I'm getting this exception: 

Umbraco.Core.Exceptions.PanicException: The existing DocumentCultureVariationDto was not found for node 2294 and language 1

I'd like to ask help on what this error means and why I'm not able to apply a document type change in Live

**Comment by jmf-umbraco** [comment] 2023-08-08 08:05
Hi Jerome,

Thanks for the report. We'll take a look into this and see if we can find an explanation for the behaviour you are seeing.

**Comment by jmf-umbraco** [comment] 2023-11-30 12:06
Hello again @romeguarin,

We have investigated further and have been unable to reproduce this issue on a fresh Heartcore instance. We believe that it may be an invalid cache or something similar affecting only your project.

If you are still experiencing the issue, your best course of action is to raise a support ticket from the Cloud portal, which will help our team understand which specific project to look into.

As this does not to be problem for other projects, I will close this issue.

**Closed by jmf-umbraco** 2023-11-30 12:06 UTC
Labels: status/needs-investigation, type/bug
