### ISSUE TITLE
Media picker 3 unavailable in Heartcore

### ISSUE THREAD

**Issue by kjsguld** [umbraco/Umbraco.Heartcore.Issues#59] opened 2022-07-07 13:43 UTC
### Issue description

Feature request inspired by https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/57 

Using the following editors in nested content is currently not possible:
 ```
var notSupported = [
            "Umbraco.Tags",
            "Umbraco.UploadField",
            "Umbraco.ImageCropper",
            "Umbraco.BlockList"
        ];
```

Of these, most importantly, the Image Cropper is not available and neither is version 3 of the Media Picker. Due to this, there are significant disadvantages over the standard CMS when building a user-friendly experience in the backoffice for editors. as one cannot fully utilize nested content.  

When would it be possible to have this introduced in the future?

**Comment by sitereactor** [comment] 2022-08-10 07:57
Planned for sprint 195 (August 15-26).

**Comment by RSoeborg** [comment] 2022-08-15 19:48
It seems that you broke our media picker on all environments

![image](https://user-images.githubusercontent.com/6117888/184706794-374c0e1e-3355-4aa5-86be-56b78e1e8446.png)

Any possibility that this is related to this issue?

**Comment by sitereactor** [comment] 2022-08-15 20:06
@RSoeborg Can you send your project alias to our support team through the chat in the Umbraco Cloud Portal? That will allow us to check. There was a deployment earlier today with an update for GraphQL, but it was not related to the media picker v3 though. But the change could be a regression, which we'd like to investigate further.

**Comment by RSoeborg** [comment] 2022-08-15 20:08
gubi-3-0

**Comment by RSoeborg** [comment] 2022-08-15 22:23
We feel a bit left in the dark since our production environment is down. Can you take a look at it @sitereactor

**Comment by sitereactor** [comment] 2022-08-15 22:23
The query from your screenshot works again. We were able to isolate the issue to an update, which was supposed to enable complex filtering for content pickers, mntp and media pickers. But due to a regression the graphql schema was not updated properly. Sorry about the inconvenience that this caused. Thanks for reaching out though. It allowed us to quickly isolate the issue and push a new deployment.

**Comment by sitereactor** [comment] 2022-08-15 22:27
@RSoeborg guess we posted at the same time. I had a look and it should be fixed. Let me know if you have any queries that currently don't work. I only had the above one to test with and that works now.

**Comment by RSoeborg** [comment] 2022-08-15 22:55
Thank you  @sitereactor - Our staging environment still seems to have some issues, but production is running smoothly again.

**Comment by sitereactor** [comment] 2022-08-15 22:57
Okay, I can refresh staging and clear the cdn cache. That should get it back into shape.
I'll post here when its done.

**Comment by sitereactor** [comment] 2022-08-15 23:05
Staging environment has been refreshed.
The query from above works on Staging, so would expect it to back in shape.

**Comment by RSoeborg** [comment] 2022-08-15 23:09
Hi @sitereactor It's working again. Thanks for the help! 👍

**Comment by sitereactor** [comment] 2022-08-25 08:59
Support for Media Picker v3 is scheduled to be released August 29th.

**Comment by jeppeschibsted** [comment] 2022-08-25 09:00
And the other items?

**Comment by sitereactor** [comment] 2022-08-25 09:06
The unsupported items remain unsupported. We are adding Media Picker v3 because that is supported and should super seed the need for ImageCropper and Upload field.

I believe the feature request was specifically for Media Picker v3. 
Block List within Nested Content doesn't really make sense.
Tags is something we can look into if needed

**Comment by sitereactor** [comment] 2022-08-25 09:07
FWIW, all of the items listed as not supported are from the standard cms and would be the same regardless of which variation of Umbraco is used.

**Comment by jeppeschibsted** [comment] 2022-08-25 09:08
Well.. The feature request for all of those, and the most important one was Image Cropper. 
Which is what was written.
The comment saying it was scheduled for release tomorrow, did not mention that none of the items would actually be fixed.

**Comment by jeppeschibsted** [comment] 2022-08-25 09:11
I care mostly about tags and imagecropper. I have not tried the media picker v3, but maybe it has the same features as the image cropper? If so, great, if not, not great.
Communication about the fix for this issue has not been totally awesome.

**Comment by sitereactor** [comment] 2022-08-25 09:57
>Well.. The feature request for all of those, and the most important one was Image Cropper.
Which is what was written.
The comment saying it was scheduled for release tomorrow, did not mention that none of the items would actually be fixed.

Yes, I should have been more explicit about what was being added as part of the work done around this feature request.
It was my understanding that the missing support for Media Picker v3 was the primary issue.

>I care mostly about tags and imagecropper. I have not tried the media picker v3, but maybe it has the same features as the image cropper? If so, great, if not, not great.

Media Picker v3 has cropping capabilities built-in, so that should be the way forward for using image crops within nested content.

>Communication about the fix for this issue has not been totally awesome.

Yes, thats on me as I have been a bit preoccupied with an issue from last week where an update didn't go as planned (hence the other comments above), so the update including media picker v3 has been pushed a bit as we improved and expanded testing capabilities prior to releasing more GraphQL related updates.

>You might want to update your documentation on tags and imagecropper, and make it more clear that these fields are not supported in every document type.

That's fair and happy to revisit the documentation, but this is about support for certain Property Editors within a Property Editor, which are somewhat special cases. Nested Content is a Property Editor that can use other Property Editors to make up an element that can be nested. I understand that the limitations are not super transparent, which is of course not good enough from our side. It should definitely be more transparent what is possible and not possible when creating a Document Type for use in Nested Content.

With regards to using tags, its a limitation in the Tags Property Editor that it cannot be used within Nested Content, because of how the tag values are saved. So its not something we can just enable unfortauntely.
An alternative could be to use the Contentment Data List Property Editor, which has a Tags option. But the tags needs to be predefined, which might not work in your scenario?

**Comment by jeppeschibsted** [comment] 2022-08-25 10:17
> > Well.. The feature request for all of those, and the most important one was Image Cropper.
> > Which is what was written.
> > The comment saying it was scheduled for release tomorrow, did not mention that none of the items would actually be fixed.
> 
> Yes, I should have been more explicit about what was being added as part of the work done around this feature request. It was my understanding that the missing support for Media Picker v3 was the primary issue.

We wanted the features of the imagecropper, drag n drop to quickly upload an image, without the need for it to go to the media library first. I use case we discussed in a meeting with @kjsguld 

> 
> > I care mostly about tags and imagecropper. I have not tried the media picker v3, but maybe it has the same features as the image cropper? If so, great, if not, not great.
> 
> Media Picker v3 has cropping capabilities built-in, so that should be the way forward for using image crops within nested content.
> 
> > Communication about the fix for this issue has not been totally awesome.
> 
> Yes, thats on me as I have been a bit preoccupied with an issue from last week where an update didn't go as planned (hence the other comments above), so the update including media picker v3 has been pushed a bit as we improved and expanded testing capabilities prior to releasing more GraphQL related updates.
> 
> > You might want to update your documentation on tags and imagecropper, and make it more clear that these fields are not supported in every document type.
> 
> That's fair and happy to revisit the documentation, but this is about support for certain Property Editors within a Property Editor, which are somewhat special cases. Nested Content is a Property Editor that can use other Property Editors to make up an element that can be nested. I understand that the limitations are not super transparent, which is of course not good enough from our side. It should definitely be more transparent what is possible and not possible when creating an Element Type for use in Nested Content.

Having the possibility to nest content is the primary use case for us. Not having the ability to nest certain types of content, which is not described in documentation, and only discovered upon use is not optimal. These lacking features were, as far as I recall, also a surprise to your chat support. It was a big surprise to us aswell. 

> 
> With regards to using tags, its a limitation in the Tags Property Editor that it cannot be used within Nested Content, because of how the tag values are saved. So its not something we can just enable unfortauntely. An alternative could be to use the Contentment Data List Property Editor, which has a Tags option. But the tags needs to be predefined, which might not work in your scenario?

The tags are editor defined, and used elsewhere in our document types. This feature was also discussed with @kjsguld in a meeting. 
Since there is also no way for us to actually retrieve all tags from a tag editor, we cannot setup a Contentment data list with a list of all our tags.
Well... I guess we could our selves index all of our content in your CMS, and create a list of tags that have been created by our editors, and then publish that on a public endpoint somewhere, so that we can use it in your CMS... But then again....

**Comment by sitereactor** [comment] 2022-08-30 16:06
After todays update roll-out the Media Picker v3 property editor is now available in Umbraco Heartcore with GraphQL support.
This property editor can be used within Nested Content. So I will close this feature request as done.

With regards to the discussion about support for tags within Nested Content we'll treat that as a separate feature request, which we will investigate. I expect that its something we can add to Heartcore to cater for this feature request until Umbraco ships with a Tags property editor that can be used within Nested Content and the Block List Editor.

**Closed by sitereactor** 2022-08-30 16:06 UTC
Labels: state/sprint-candidate

**Comment by jeppeschibsted** [comment] 2022-08-31 07:16
Hi. I have tried the new Media Picker, I think. There are two Media Pickers available, one called just "Media Picker" and one called "Media Picker (legacy)". I suspect that the new one, v3, is the one that is not called legacy? This one does not have drag n drop upload which was specifically what we had discussed with @kjsguld 
If this is the new version, there is not really anything new in it, that solves our problem unfortunately.
